// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyeCnJrPjt9yZNcnKu1z1z4gfH95-eHIM',
    appId: '1:698808322515:web:04f72c86aeae3ad61d4726',
    messagingSenderId: '698808322515',
    projectId: 'final-year-project-257e7',
    authDomain: 'final-year-project-257e7.firebaseapp.com',
    storageBucket: 'final-year-project-257e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDdPCLF5rtjmYmNeBbMRfo0ZQhU3XiB0',
    appId: '1:698808322515:android:31d7c44c22d0df0f1d4726',
    messagingSenderId: '698808322515',
    projectId: 'final-year-project-257e7',
    storageBucket: 'final-year-project-257e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlqXhjCiAlMmLL86P4Cm6fzezNochgHU8',
    appId: '1:698808322515:ios:a8c1889a8fada4f71d4726',
    messagingSenderId: '698808322515',
    projectId: 'final-year-project-257e7',
    storageBucket: 'final-year-project-257e7.firebasestorage.app',
    iosBundleId: 'com.example.luma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlqXhjCiAlMmLL86P4Cm6fzezNochgHU8',
    appId: '1:698808322515:ios:a8c1889a8fada4f71d4726',
    messagingSenderId: '698808322515',
    projectId: 'final-year-project-257e7',
    storageBucket: 'final-year-project-257e7.firebasestorage.app',
    iosBundleId: 'com.example.luma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyeCnJrPjt9yZNcnKu1z1z4gfH95-eHIM',
    appId: '1:698808322515:web:2a39a351c0b750281d4726',
    messagingSenderId: '698808322515',
    projectId: 'final-year-project-257e7',
    authDomain: 'final-year-project-257e7.firebaseapp.com',
    storageBucket: 'final-year-project-257e7.firebasestorage.app',
  );

}